Vagrant.configure("2") do |config|

    config.dns.tld = "mydomain"
    config.vm.hostname = "mymachine"

    config.vm.box = "bento/ubuntu-20.04"
    config.vm.synced_folder "./springApplication/h2data", "/home/vagrant/h2data"

    config.vm.network "forwarded_port", guest: 8080, host: 1010

end

