pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling the latest source code from the development branch'
                checkout scm
            }
        }

        stage('Assemble') {
            steps {
                dir('ca6/springApplication') {
                    echo 'Making gradlew executable'
                    sh 'chmod +x gradlew' // Add this line to make gradlew executable

                    echo 'Compiling the code and building artifact files'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ca6/springApplication') {
                    echo 'Making gradlew executable'
                    sh 'chmod +x gradlew' // Ensure this step is repeated in case of separate environments

                    echo 'Running unit tests to verify the application’s correctness'
                    sh './gradlew test'

                    echo 'Publishing test results in Jenkins'
                    junit '**/build/test-results/test/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('ca6/springApplication') {
                    echo 'Archiving the built artifacts'
                    archiveArtifacts artifacts: 'app/build/libs/*.jar', allowEmptyArchive: false
                }
            }
        }

        stage('Deploy to Production?') {
            steps {
                script {
                    echo 'Requesting manual approval for deployment to production'
                    timeout(time: 30, unit: 'MINUTES') {
                        input message: 'Do you approve the deployment to production?', ok: 'Proceed'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('ca6/springApplication') {
                    echo 'Deploying the application using Ansible playbook'
                    sh 'ansible-playbook -i inventory/hosts deploy.yml --extra-vars "target=green_vm"'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed'
        }
        success {
            echo 'Pipeline succeeded'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
