Vagrant.configure("2") do |config|

    config.dns.tld = "mydomain"
    config.vm.hostname = "mymachine"

    config.vm.define "app" do |app|
        app.vm.box = "bento/ubuntu-20.04"

        app.vm.provision "shell", path: "requirements.sh"
        app.vm.provision "shell", path: "configure_spring.sh"
        app.vm.network "private_network", type: "dhcp"
        app.vm.hostname = "app"

        app.vm.provision "shell", path: "wait_for_db.sh"


        app.vm.provision "shell" do |s|
        s.env = {
            "CLONE_REPO" => "true",
            "START_REST_SERVICE" => "true",
            "START_CHAT_SERVICE" => "false",
        }
        s.path = "services.sh"
        end

        # Add the provisioning script to configure Spring Boot properties
        #pp.vm.provision "shell", path: "configure_spring.sh"
    end

    config.vm.define "db" do |db|
        db.vm.box = "bento/ubuntu-20.04"

        config.vm.synced_folder "./h2data", "/home/vagrant/h2data"

        #db.memory = "1024"
        #db.cpus = 1

        #config.disksize.size = '5 GB'

        db.vm.provision "shell", path: "install_h2.sh"
        db.vm.network "forwarded_port", guest: 9092, host: 1013
        db.vm.network "forwarded_port", guest: 8082, host: 1014

        db.vm.hostname = "database"
        db.vm.network "private_network", type: "dhcp"
    end

end
