# Stage 1: Build stage
FROM openjdk:17-jdk-slim as build

# Install build dependencies
RUN apt-get update && \
    apt-get install -y wget unzip git && \
    wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-7.6-bin.zip && \
    rm /tmp/gradle-7.6-bin.zip && \
    ln -s /opt/gradle/gradle-7.6/bin/gradle /usr/bin/gradle

# Set environment variables for Gradle
ENV GRADLE_HOME /opt/gradle/gradle-7.6
ENV PATH ${GRADLE_HOME}/bin:$PATH

# Clone the repository
RUN git clone https://github.com/ruben1191018/cogsi-1190914-1191018-1191042.git /app

# Set the working directory to the project folder
WORKDIR /app/ca2/part1/gradle_basic_demo-main

# Build the project with Gradle
RUN gradle build

# Stage 2: Runtime stage
FROM openjdk:17-jdk-slim

# Copy the built JAR file from the build stage
COPY --from=build /app/ca2/part1/gradle_basic_demo-main/build/libs/basic_demo-0.1.0.jar /app/app.jar

# Expose the port the Spring Boot app runs on
EXPOSE 59001

# Run the application
ENTRYPOINT ["java", "-cp", "/app/app.jar", "basic_demo.ChatServerApp", "59001"]
